<?php

// Reports hub (client request 2026-08-05).
// Note: TranslationParitySentinelTest fails if a key exists here and not in
// lang/es/reports.php, or the other way around.
return [
    // Navigation / screen
    'nav' => 'Reports',
    'title' => 'Reports',
    'which_report' => 'Which report',
    'report' => 'Report',
    'report_costs' => 'Maintenance costs',
    'report_category_inventory' => 'Inventory by category',

    // Period
    'period' => 'Period',
    'period_help' => 'Spend is counted by the work order completion date. Included work orders that are still open are counted by their opening date.',
    'quick_period' => 'Shortcut',
    'this_month' => 'This month',
    'last_month' => 'Last month',
    'last_3_months' => 'Last 3 months',
    'this_year' => 'This year',
    'custom' => 'Custom',
    'from' => 'From',
    'to' => 'To',

    // Filters
    'filters' => 'Filters',
    'machines' => 'Machines',
    'machines_help' => 'Picked from the machines on file. With none ticked, all of them are included.',
    'locations' => 'Job sites',
    'location_help' => 'The job site recorded on the work order, not where the machine is today.',
    'completed_by' => 'Performed the maintenance',
    'completed_by_help' => 'Whoever closed the work order. Work orders closed before August 5, 2026 do not carry this data.',
    'statuses_help' => 'Completed only by default: the cost of an open work order can still change.',
    'selected' => 'selected',
    'applied_filters' => 'Applied filters',

    // Downloads
    'download_pdf' => 'Download PDF',
    'download_excel' => 'Download Excel',
    'generated_by' => 'Generated by',

    // Totals
    'total_spent' => 'Total spend',
    'parts_only' => 'parts only',
    'machines_with_spend' => 'Machines',
    'work_orders' => 'Work orders',
    'labor_hours' => 'Labor hours',
    'not_priced' => 'not priced',
    'parts_spend' => 'Parts spend',
    'machine_spend' => 'Machine spend',
    'grand_total' => 'Grand total',
    'total' => 'Total',
    'subtotal_parts' => 'Parts subtotal',
    'tax_amount_label' => 'Tax (:rate%)',
    'grand_total_with_tax' => 'Total (with tax)',

    // Detail
    'detail' => 'Detail by machine',
    'detail_help' => 'Pick a machine to see its work orders for the period: what work was done, by whom, where, and what was spent.',
    'detail_machine' => 'Machine',
    'detail_pick_machine' => 'Pick a machine',
    'detail_none_selected' => 'Pick a machine above to see its detail.',
    'detail_machine_gone' => 'The machine you picked does not show up with the current filters. Pick another one.',
    'detail_spend' => 'Spent in the period',
    'work_description' => 'Work',
    'no_description' => 'No description entered on the work order.',
    'job_number' => 'Job number',
    'detail_in_files' => 'This is the full detail of the machine you picked (who, where, checklist and each part). All of them together are in the PDF and the Excel file.',
    'print' => 'Print',
    'checklist_ok_badge' => 'Approved',
    'checklist_alert_badge' => 'With findings',
    'location' => 'Job site',
    'checklist' => 'Checklist',
    'checklist_total' => 'Checklist items',
    'checklist_alerts' => 'Items flagged',
    'items' => 'items',
    'no_checklist' => 'No checklist performed.',
    'part_number' => 'Part number',
    'part_description' => 'Part',
    'quantity' => 'Quantity',
    'unit_cost' => 'Unit cost',
    'subtotal' => 'Subtotal',
    'wo_total' => 'Work order total',
    'no_parts' => 'No parts recorded.',
    'no_results' => 'No work orders match these filters in this period.',

    // Integrity notices
    'not_recorded' => 'Not recorded',
    'no_cost_loaded' => 'no cost recorded',
    'data_gaps' => 'What this report cannot answer',
    'gap_parts_without_cost' => ':count part(s) recorded with no unit cost: that is real spend the total does NOT include.',
    'gap_unknown_completer' => ':count work order(s) with no record of who performed the maintenance.',
    'gap_unknown_location' => ':count work order(s) with no record of which job site it was done at.',
    'uncategorized_notice' => 'There are :count machine(s) with no type assigned, so the category counts do not add up to the fleet total.',

    // Footers
    'footer_note' => 'Spend means parts: quantity × unit cost of every part recorded on the work order. Labor is reported in hours and is not priced, because the system has no hourly rate defined. Generated by the DP Development Fleet Maintenance System.',
    'category_footer_note' => 'Includes categories with no machines, so empty ones can be verified. Retired machines are excluded. Generated by the DP Development Fleet Maintenance System.',
];
